version: '3'

services:
  nginx:
    container_name: pw_local_env-nginx
    image: nginx:1.17.6-alpine
    restart: unless-stopped
    ports:
      - "8030:8080"
    volumes:
      - .:/app
      - ./etc/nginx/default.conf:/etc/nginx/conf.d
    depends_on:
      - app
      

  app:
    container_name: pw_local_env-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9030:9001"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: pw_local_env-db
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3330:3306"
    env_file:
      - .env

  admin:
    container_name: pw_local_env-admin
    image: adminer
    restart: always
    ports:
      - 8090:8060
    depends_on:
      - db

